# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7998e6358ff8c208f0ca0895922924db4d7370faf37f19af7c1eb345b7a6775c4cc70a39a143ebf76b75ea0c3eb184281beaaf1420443910f4d59fde6b122b58

test:
  secret_key_base: 5f51839db255c391ef2e82e44b3034f0f3ae5a5d07c578da8a3f6ae9424d914776ae8e856d0067dd27841f6e8ef3dfe04b9b457818077ec443025abaa7940935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
